import XCTest
@testable import GraptionCore

final class GraptionCoreTests: XCTestCase {
    func testEventDecoding() throws {
        // 1. Provide sample JSON strings matching your schema for each event type

    
    let sampleSpeakerScoresJson = """
    {
        "type": "speaker_scores",
        "session_id": "session-xyz",
        "schema_version": "1.0",
        "t": 4.5,
        "faces": [
            {
            "face_id": "f1",
            "p": 0.85,
            "bbox": [10.0, 20.0, 150.0, 200.0]
            }
        ]
    }
    """.data(using: .utf8)!

    let sampleCaptionJson = """
    {
        "type": "caption",
        "session_id": "session-xyz",
        "schema_version": "1.0",
        "caption_id": "12345678-abcd-ef01-2345-6789abcdef01",
        "t_start": 1.0,
        "t_end": 3.5,
        "text": "Hello world",
        "speaker_id": "f1",
        "model_versions": {
        "asr": "whisperkit-base.en",
        "asd": "asd-v3" 
        }
    }
    """.data(using: .utf8)!

    let sampleSoundEventJson = """
    {
        "type": "sound_event",
        "session_id": "session-xyz",
        "schema_version": "1.0",
        "t": 12.4,
        "label": "doorbell",
        "confidence": 0.92
    }
    """.data(using: .utf8)!

    let sampleToneRequestJson = """
    {
        "type": "tone_request",
        "session_id": "session-xyz",
        "schema_version": "1.0",
        "caption_id": "12345678-abcd-ef01-2345-6789abcdef01",
        "t_start": 1.0,
        "t_end": 3.5,
        "sample_rate": 16000,
        "audio_b64": "SGVsbG8="
    }
    """.data(using: .utf8)!

    let sampleCaptionLogJson = """
    {
        "type": "caption_log",
        "session_id": "session-xyz",
        "schema_version": "1.0",
        "caption": {
            "type": "caption",
            "session_id": "session-xyz",
            "schema_version": "1.0",
            "caption_id": "12345678-abcd-ef01-2345-6789abcdef01",
            "t_start": 1.0,
            "t_end": 3.5,
            "text": "Hello world",
            "speaker_id": "f1",
            "model_versions": { "asr": "whisperkit-base.en", "asd": "asd-v3" }
        },
        "tone_tag": "excited"
    }
    """.data(using: .utf8)!

    let sampleToneResultJson = """
    {
        "type": "speaker_scores",
        "session_id": "session-xyz",
        "schema_version": "1.0",
        "t": 4.5,
        "faces": [
            {
            "face_id": "f1",
            "p": 0.85,
            "bbox": [10.0, 20.0, 150.0, 200.0]
            }
        ]
    }
    """.data(using: .utf8)!



        // 2. Attempt to decode it using JSONDecoder and the struct generated by quicktype
        // Replace 'YourGeneratedEventStruct' with the actual top-level struct name from Events.swift
        let decoder = JSONDecoder()
        XCTAssertNoThrow(try decoder.decode(Events.self, from: sampleSpeakerScoresJson))
        XCTAssertNoThrow(try decoder.decode(Events.self, from: sampleCaptionJson))
        XCTAssertNoThrow(try decoder.decode(Events.self, from: sampleSoundEventJson))
        XCTAssertNoThrow(try decoder.decode(Events.self, from: sampleToneRequestJson))
        XCTAssertNoThrow(try decoder.decode(Events.self, from: sampleCaptionLogJson))
        XCTAssertNoThrow(try decoder.decode(Events.self, from: sampleToneResultJson))
    }

    func testClockSavesTime() {
        let clock = SessionClock()
        Thread.sleep(forTimeInterval: 1.0)
        XCTAssertGreaterThanOrEqual(clock.secondsElapsed, 1.0)
    }
}
