# generated by datamodel-codegen:
#   filename:  events.schema.json

from __future__ import annotations

from typing import Annotated, Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, RootModel
from typing_extensions import TypeAliasType


class SchemaVersion(RootModel[Literal["1.0"]]):
    root: Literal["1.0"]


class SessionId(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class Seconds(RootModel[float]):
    root: Annotated[float, Field(ge=0.0)]


class Probability(RootModel[float]):
    root: Annotated[float, Field(ge=0.0, le=1.0)]


class CaptionId(RootModel[UUID]):
    root: UUID


class FaceId(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="Per-session track id assigned by FaceTracker: f1, f2, ...",
            pattern="^f[1-9][0-9]*$",
        ),
    ]


class FaceScore(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    face_id: FaceId
    p: Annotated[Probability, Field(description="Smoothed p(speaking).")]
    bbox: Annotated[list[float], Field(description="[x, y, w, h]", max_length=4, min_length=4)]


class SpeakerScores(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["speaker_scores"]
    session_id: SessionId
    schema_version: SchemaVersion
    t: Seconds
    faces: list[FaceScore]


class ModelVersions(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    __annotations__ = {
        "__pydantic_extra__": dict[str, str],
    }
    asr: Annotated[str, Field(examples=["whisperkit-base.en"])]
    asd: Annotated[str, Field(examples=["asd-v3"])]


class Caption(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["caption"]
    session_id: SessionId
    schema_version: SchemaVersion
    caption_id: CaptionId
    t_start: Seconds
    t_end: Seconds
    text: str
    speaker_id: Annotated[
        FaceId | Literal["unknown"],
        Field(
            description='Face id chosen by fusion, or "unknown" (off-screen/ambiguous; shown as "Someone").'
        ),
    ]
    model_versions: ModelVersions


class SoundEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["sound_event"]
    session_id: SessionId
    schema_version: SchemaVersion
    t: Seconds
    label: Annotated[str, Field(examples=["doorbell"])]
    confidence: Probability


class ToneRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["tone_request"]
    session_id: SessionId
    schema_version: SchemaVersion
    caption_id: CaptionId
    t_start: Seconds
    t_end: Seconds
    sample_rate: Annotated[int, Field(examples=[16000], ge=1)]
    audio_b64: Annotated[
        str,
        Field(
            description="PCM16 mono little-endian. Never written to disk or logs.",
            json_schema_extra={"contentEncoding": "base64"},
        ),
    ]


class CaptionLog(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["caption_log"]
    session_id: SessionId
    schema_version: SchemaVersion
    caption: Caption
    tone_tag: Annotated[str | None, Field(examples=["excited"])]


class Probs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    anger: Probability
    disgust: Probability
    fear: Probability
    happy: Probability
    neutral: Probability
    sad: Probability


LatencyMsAdditionalProperty = TypeAliasType(
    "LatencyMsAdditionalProperty", Annotated[float, Field(ge=0.0)]
)


class LatencyMs(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    __annotations__ = {
        "__pydantic_extra__": dict[str, LatencyMsAdditionalProperty],
    }
    recv_to_send: Annotated[float, Field(ge=0.0)]


class ToneResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["tone_result"]
    session_id: SessionId
    schema_version: SchemaVersion
    caption_id: CaptionId
    tag: Annotated[str | None, Field(examples=["happy"])]
    probs: Probs
    model_version: Annotated[str, Field(examples=["tone-head-v2"])]
    latency_ms: LatencyMs


class GraptionEvent(
    RootModel[SpeakerScores | Caption | SoundEvent | ToneRequest | CaptionLog | ToneResult]
):
    root: Annotated[
        SpeakerScores | Caption | SoundEvent | ToneRequest | CaptionLog | ToneResult,
        Field(
            description="Graption event contract v1.0 (docs/GRAPTION_CONTEXT.md section 5). All times are seconds since session start on the phone's monotonic host clock. Changing this file = bump schema_version and regenerate Pydantic + Swift types.",
            title="GraptionEvent",
        ),
    ]
